$(document).ready(function () {
    $("button#javS").click(function() {
        $("#java").fadeToggle();
        $("#javS").toggle();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#java").click(function(){
        $("#javS").show();
        $("#java").hide();
    })
    $("button#operate").click(function () {
        $("#operator").fadeToggle();
        $("#operate").toggle();
        $("#java").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#operator").click(function(){
        $("#operate").show();
        $("#operator").hide();
    })
    $("button#vary").click(function () {
        $("#variable").fadeToggle();
        $("#vary").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#variable").click(function(){
        $("#vary").show();
        $("#variable").hide();
    })
    $("button#convent").click(function () {
        $("#convention").fadeToggle();
        $("#convent").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#convention").click(function(){
        $("#convent").show();
        $("#convention").hide();
    })
    $("button#ftn").click(function () {
        $("#function").slideToggle();
        $("#ftn").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#function").click(function(){
        $("#ftn").show();
        $("#function").hide();
    })
    $("button#meth").click(function () {
        $("#method").slideToggle();
        $("#meth").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#method").click(function(){
        $("#meth").show();
        $("#method").hide();
    })
    $("button#argue").click(function () {
        $("#arg").slideToggle();
        $("#argue").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#arg").click(function(){
        $("#argue").show();
        $("#arg").hide();
    })
    $("button#param").click(function () {
        $("#params").slideToggle();
        $("#param").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#params").click(function(){
        $("#param").show();
        $("#params").hide();
    })
    $("button#rtn").click(function () {
        $("#rtns").slideToggle();
        $("#rtn").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#rtns").click(function(){
        $("#rtn").show();
        $("#rtns").hide();
    })
    $("button#ch-meth").click(function () {
        $("#ch-method").slideToggle();
        $("#ch-meth").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#ch-method").click(function(){
        $("#ch-meth").show();
        $("#ch-method").hide();
    })
    $("button#strg").click(function () {
        $("#strgs").slideToggle();
        $("#strg").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#strgs").click(function(){
        $("#strg").show();
        $("#strgs").hide();
    })
    $("button#true").click(function () {
        $("#false").slideToggle();
        $("#true").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#false").click(function(){
        $("#true").show();
        $("#false").hide();
    })
    $("button#undef").click(function () {
        $("#undefs").slideToggle();
        $("#undef").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#undefs").click(function(){
        $("#undef").show();
        $("#undefs").hide();
    })
    $("button#not").click(function () {
        $("#notNumber").slideToggle();
        $("#not").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#notNumber").click(function(){
        $("#not").show();
        $("#notNumber").hide();
    })
    $("button#nothing").click(function () {
        $("#nullthing").slideToggle();
        $("#nothing").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#dong").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#nullthing").click(function(){
        $("#nothing").show();
        $("#nullthing").hide();
    })
    $("button#ding").click(function () {
        $("#dong").slideToggle();
        $("#ding").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#comnts").hide();
        $("#jq").hide();
    })
    $("#dong").click(function(){
        $("#ding").show();
        $("#dong").hide();
    })
    $("button#comnt").click(function () {
        $("#comnts").slideToggle();
        $("#comnt").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#jq").hide();
    })
    $("#comnts").click(function(){
        $("#comnt").show();
        $("#comnts").hide();
    })
    $("button#jque").click(function () {
        $("#jq").slideToggle();
        $("#jque").toggle();
        $("#java").hide();
        $("#operator").hide();
        $("#variable").hide();
        $("#convention").hide();
        $("#function").hide();
        $("#method").hide();
        $("#arg").hide();
        $("#params").hide();
        $("#rtns").hide();
        $("#ch-method").hide();
        $("#strgs").hide();
        $("#false").hide();
        $("#undefs").hide();
        $("#notNumber").hide();
        $("#nullthing").hide();
        $("#dong").hide();
        $("#comnts").hide();
    })
    $("#jq").click(function(){
        $("#jque").show();
        $("#jq").hide();
    })
})